# Generated by Django 5.0.2 on 2024-02-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_explanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explanation',
            name='name',
        ),
        migrations.AddField(
            model_name='explanation',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
